.class public Lcom/facebook/common/classmarkers/loaders/LoadersModule$AutoGeneratedBindingsForLoadersModule;
.super Ljava/lang/Object;
.source ""


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 0
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 1
    .line 2
    .line 3
    return-void
.end method

.method public static bind(LX/2FP;)V
    .locals 0

    .line 0
    return-void
.end method
