.class public Lcom/facebook/acra/criticaldata/setter/AcraCriticalDataModule$AutoGeneratedBindingsForAcraCriticalDataModule;
.super Ljava/lang/Object;
.source ""


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 36377
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static bind(LX/1iV;)V
    .locals 0

    .line 36378
    return-void
.end method
