.class public final LX/3gl;
.super Ljava/lang/Object;
.source ""


# annotations
.annotation build Lcom/facebook/ultralight/AutoGeneratedSwitchAppModuleSubClass;
    value = 0xb
.end annotation


# direct methods
.method public static A00(ILX/0kw;)Ljava/lang/Object;
    .locals 1

    shr-int/lit8 v0, p0, 0x7

    and-int/lit8 v0, v0, 0xf

    if-nez v0, :cond_0

    invoke-static {p0, p1}, LX/3gl;->A01(ILX/0kw;)Ljava/lang/Object;

    move-result-object v0

    return-object v0

    :cond_0
    new-instance p0, Ljava/lang/IllegalArgumentException;

    const-string v0, "Invalid Static DI binding id"

    invoke-direct {p0, v0}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw p0
.end method

.method public static A01(ILX/0kw;)Ljava/lang/Object;
    .locals 0

    shr-int/lit8 p0, p0, 0x0

    and-int/lit8 p0, p0, 0x7f

    packed-switch p0, :pswitch_data_0

    :pswitch_0
    new-instance p1, Ljava/lang/IllegalArgumentException;

    const-string p0, "Invalid Static DI binding id"

    invoke-direct {p1, p0}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw p1

    :pswitch_1
    invoke-static {p1}, LX/RaR;->A00(LX/0kw;)LX/RaR;

    move-result-object p0

    return-object p0

    :pswitch_2
    invoke-static {p1}, LX/RY0;->A00(LX/0kw;)LX/RY0;

    move-result-object p0

    return-object p0

    :pswitch_3
    invoke-static {p1}, LX/RSs;->A00(LX/0kw;)LX/7jy;

    move-result-object p0

    return-object p0

    :pswitch_4
    invoke-static {p1}, LX/RaH;->A00(LX/0kw;)LX/RaH;

    move-result-object p0

    return-object p0

    :pswitch_5
    invoke-static {p1}, LX/RWt;->A00(LX/0kw;)LX/RWt;

    move-result-object p0

    return-object p0

    :pswitch_6
    invoke-static {p1}, LX/RUu;->A01(LX/0kw;)LX/RUu;

    move-result-object p0

    return-object p0

    :pswitch_7
    invoke-static {p1}, LX/RTq;->A00(LX/0kw;)LX/RTq;

    move-result-object p0

    return-object p0

    :pswitch_8
    invoke-static {p1}, LX/RYU;->A00(LX/0kw;)LX/RYU;

    move-result-object p0

    return-object p0

    :pswitch_9
    invoke-static {p1}, LX/RT0;->A00(LX/0kw;)LX/7ko;

    move-result-object p0

    return-object p0

    :pswitch_a
    invoke-static {p1}, LX/RXp;->A00(LX/0kw;)LX/RXp;

    move-result-object p0

    return-object p0

    :pswitch_b
    invoke-static {p1}, LX/RWM;->A00(LX/0kw;)LX/RWM;

    move-result-object p0

    return-object p0

    :pswitch_c
    invoke-static {p1}, LX/RVu;->A00(LX/0kw;)LX/RVu;

    move-result-object p0

    return-object p0

    :pswitch_d
    invoke-static {p1}, LX/RXO;->A00(LX/0kw;)LX/RXO;

    move-result-object p0

    return-object p0

    :pswitch_e
    invoke-static {p1}, LX/RYM;->A00(LX/0kw;)LX/RYM;

    move-result-object p0

    return-object p0

    :pswitch_f
    invoke-static {p1}, LX/RZY;->A00(LX/0kw;)LX/RZY;

    move-result-object p0

    return-object p0

    :pswitch_10
    invoke-static {p1}, LX/RYY;->A00(LX/0kw;)LX/RYY;

    move-result-object p0

    return-object p0

    :pswitch_11
    invoke-static {p1}, LX/RbI;->A00(LX/0kw;)LX/RbI;

    move-result-object p0

    return-object p0

    :pswitch_12
    invoke-static {p1}, LX/RZ5;->A00(LX/0kw;)LX/RZ5;

    move-result-object p0

    return-object p0

    :pswitch_13
    invoke-static {p1}, LX/RZh;->A00(LX/0kw;)LX/RZd;

    move-result-object p0

    return-object p0

    :pswitch_14
    invoke-static {p1}, LX/RTB;->A03(LX/0kw;)LX/7kp;

    move-result-object p0

    return-object p0

    :pswitch_15
    invoke-static {p1}, LX/RYz;->A00(LX/0kw;)LX/RYz;

    move-result-object p0

    return-object p0

    :pswitch_16
    invoke-static {p1}, LX/RZz;->A00(LX/0kw;)LX/RZz;

    move-result-object p0

    return-object p0

    :pswitch_17
    invoke-static {p1}, LX/RVr;->A01(LX/0kw;)LX/RVr;

    move-result-object p0

    return-object p0

    :pswitch_18
    invoke-static {p1}, LX/RVa;->A00(LX/0kw;)LX/RVa;

    move-result-object p0

    return-object p0

    :pswitch_19
    invoke-static {p1}, LX/RZg;->A01(LX/0kw;)LX/RZg;

    move-result-object p0

    return-object p0

    :pswitch_1a
    new-instance p0, LX/RV4;

    invoke-direct {p0, p1}, LX/RV4;-><init>(LX/0kw;)V

    return-object p0

    :pswitch_1b
    invoke-static {}, LX/RWp;->A00()LX/RWp;

    move-result-object p0

    return-object p0

    :pswitch_1c
    invoke-static {}, LX/RV1;->A00()LX/RV1;

    move-result-object p0

    return-object p0

    :pswitch_1d
    invoke-static {p1}, LX/RaQ;->A00(LX/0kw;)LX/RaQ;

    move-result-object p0

    return-object p0

    :pswitch_1e
    invoke-static {p1}, LX/RXf;->A00(LX/0kw;)LX/RXf;

    move-result-object p0

    return-object p0

    :pswitch_1f
    invoke-static {p1}, LX/RZ3;->A00(LX/0kw;)LX/RZ3;

    move-result-object p0

    return-object p0

    :pswitch_20
    invoke-static {p1}, LX/RYd;->A00(LX/0kw;)LX/RYd;

    move-result-object p0

    return-object p0

    :pswitch_21
    new-instance p0, LX/RW8;

    invoke-direct {p0, p1}, LX/RW8;-><init>(LX/0kw;)V

    return-object p0

    :pswitch_22
    invoke-static {p1}, LX/RVM;->A00(LX/0kw;)LX/RVM;

    move-result-object p0

    return-object p0

    :pswitch_23
    invoke-static {p1}, LX/RYB;->A00(LX/0kw;)LX/RYB;

    move-result-object p0

    return-object p0

    :pswitch_24
    invoke-static {p1}, LX/RVw;->A00(LX/0kw;)LX/RVw;

    move-result-object p0

    return-object p0

    :pswitch_25
    invoke-static {p1}, LX/Rax;->A01(LX/0kw;)LX/Rax;

    move-result-object p0

    return-object p0

    :pswitch_26
    invoke-static {p1}, LX/RTB;->A06(LX/0kw;)LX/7kr;

    move-result-object p0

    return-object p0

    :pswitch_27
    invoke-static {p1}, LX/Rag;->A01(LX/0kw;)LX/Rag;

    move-result-object p0

    return-object p0

    :pswitch_28
    invoke-static {p1}, LX/RXI;->A00(LX/0kw;)LX/RXI;

    move-result-object p0

    return-object p0

    :pswitch_29
    invoke-static {p1}, LX/RSY;->A00(LX/0kw;)LX/RSY;

    move-result-object p0

    return-object p0

    :pswitch_2a
    invoke-static {p1}, LX/Ra9;->A00(LX/0kw;)LX/Ra9;

    move-result-object p0

    return-object p0

    :pswitch_2b
    invoke-static {p1}, LX/Rap;->A00(LX/0kw;)LX/Rap;

    move-result-object p0

    return-object p0

    :pswitch_2c
    invoke-static {p1}, LX/RZA;->A00(LX/0kw;)LX/RZA;

    move-result-object p0

    return-object p0

    :pswitch_2d
    invoke-static {p1}, LX/RVc;->A00(LX/0kw;)LX/RVc;

    move-result-object p0

    return-object p0

    :pswitch_2e
    invoke-static {p1}, LX/RY1;->A00(LX/0kw;)LX/RY1;

    move-result-object p0

    return-object p0

    :pswitch_2f
    invoke-static {p1}, LX/RSv;->A02(LX/0kw;)LX/RSv;

    move-result-object p0

    return-object p0

    :pswitch_30
    invoke-static {p1}, LX/RaU;->A00(LX/0kw;)LX/RaU;

    move-result-object p0

    return-object p0

    :pswitch_31
    invoke-static {p1}, LX/RXM;->A00(LX/0kw;)LX/RXM;

    move-result-object p0

    return-object p0

    :pswitch_32
    invoke-static {p1}, LX/RTB;->A02(LX/0kw;)LX/7kt;

    move-result-object p0

    return-object p0

    :pswitch_33
    invoke-static {p1}, LX/RTB;->A00(LX/0kw;)LX/7ku;

    move-result-object p0

    return-object p0

    :pswitch_34
    invoke-static {p1}, LX/Ra4;->A00(LX/0kw;)LX/Ra4;

    move-result-object p0

    return-object p0

    :pswitch_35
    invoke-static {p1}, LX/RaM;->A00(LX/0kw;)LX/RaM;

    move-result-object p0

    return-object p0

    :pswitch_36
    invoke-static {p1}, LX/RWK;->A00(LX/0kw;)LX/RWK;

    move-result-object p0

    return-object p0

    :pswitch_37
    invoke-static {p1}, LX/RY5;->A00(LX/0kw;)LX/RY5;

    move-result-object p0

    return-object p0

    :pswitch_38
    invoke-static {p1}, LX/RTo;->A00(LX/0kw;)LX/RTo;

    move-result-object p0

    return-object p0

    :pswitch_39
    invoke-static {p1}, LX/RXn;->A00(LX/0kw;)LX/RXn;

    move-result-object p0

    return-object p0

    :pswitch_3a
    invoke-static {p1}, LX/RaF;->A01(LX/0kw;)LX/RaF;

    move-result-object p0

    return-object p0

    :pswitch_3b
    invoke-static {p1}, LX/RTB;->A01(LX/0kw;)LX/7kw;

    move-result-object p0

    return-object p0

    :pswitch_3c
    invoke-static {p1}, LX/RTB;->A05(LX/0kw;)LX/7kx;

    move-result-object p0

    return-object p0

    :pswitch_3d
    invoke-static {p1}, LX/RVT;->A00(LX/0kw;)LX/RVT;

    move-result-object p0

    return-object p0

    :pswitch_3e
    invoke-static {p1}, LX/RV5;->A00(LX/0kw;)LX/RV5;

    move-result-object p0

    return-object p0

    :pswitch_3f
    invoke-static {p1}, LX/RUY;->A00(LX/0kw;)LX/RUY;

    move-result-object p0

    return-object p0

    :pswitch_40
    invoke-static {p1}, LX/RYv;->A00(LX/0kw;)LX/RYv;

    move-result-object p0

    return-object p0

    :pswitch_41
    invoke-static {p1}, LX/RSr;->A00(LX/0kw;)LX/RSr;

    move-result-object p0

    return-object p0

    :pswitch_42
    invoke-static {p1}, LX/RZj;->A00(LX/0kw;)LX/RZj;

    move-result-object p0

    return-object p0

    :pswitch_43
    invoke-static {p1}, LX/RXR;->A00(LX/0kw;)LX/RXR;

    move-result-object p0

    return-object p0

    :pswitch_44
    invoke-static {p1}, LX/RVe;->A00(LX/0kw;)LX/RVe;

    move-result-object p0

    return-object p0

    :pswitch_45
    invoke-static {p1}, LX/RXA;->A00(LX/0kw;)LX/RXA;

    move-result-object p0

    return-object p0

    :pswitch_46
    invoke-static {p1}, LX/RTB;->A07(LX/0kw;)LX/RWQ;

    move-result-object p0

    return-object p0

    :pswitch_47
    invoke-static {}, LX/RUs;->A00()LX/RUs;

    move-result-object p0

    return-object p0

    :pswitch_48
    invoke-static {p1}, LX/RTB;->A04(LX/0kw;)LX/7ky;

    move-result-object p0

    return-object p0

    :pswitch_49
    invoke-static {p1}, LX/RTK;->A00(LX/0kw;)LX/RTK;

    move-result-object p0

    return-object p0

    :pswitch_4a
    invoke-static {p1}, LX/RXD;->A00(LX/0kw;)LX/RXD;

    move-result-object p0

    return-object p0

    :pswitch_4b
    invoke-static {p1}, LX/RSa;->A00(LX/0kw;)LX/RSa;

    move-result-object p0

    return-object p0

    :pswitch_4c
    invoke-static {p1}, LX/RYE;->A00(LX/0kw;)LX/RYE;

    move-result-object p0

    return-object p0

    nop

    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_4c
        :pswitch_4b
        :pswitch_0
        :pswitch_4a
        :pswitch_49
        :pswitch_48
        :pswitch_0
        :pswitch_0
        :pswitch_0
        :pswitch_47
        :pswitch_46
        :pswitch_45
        :pswitch_44
        :pswitch_0
        :pswitch_0
        :pswitch_43
        :pswitch_42
        :pswitch_0
        :pswitch_41
        :pswitch_40
        :pswitch_0
        :pswitch_3f
        :pswitch_3e
        :pswitch_3d
        :pswitch_0
        :pswitch_3c
        :pswitch_3b
        :pswitch_0
        :pswitch_3a
        :pswitch_0
        :pswitch_39
        :pswitch_38
        :pswitch_0
        :pswitch_0
        :pswitch_37
        :pswitch_36
        :pswitch_35
        :pswitch_34
        :pswitch_33
        :pswitch_0
        :pswitch_0
        :pswitch_32
        :pswitch_31
        :pswitch_0
        :pswitch_30
        :pswitch_2f
        :pswitch_2e
        :pswitch_2d
        :pswitch_2c
        :pswitch_0
        :pswitch_0
        :pswitch_2b
        :pswitch_2a
        :pswitch_29
        :pswitch_28
        :pswitch_0
        :pswitch_0
        :pswitch_0
        :pswitch_27
        :pswitch_26
        :pswitch_25
        :pswitch_0
        :pswitch_24
        :pswitch_23
        :pswitch_22
        :pswitch_0
        :pswitch_0
        :pswitch_0
        :pswitch_0
        :pswitch_0
        :pswitch_0
        :pswitch_21
        :pswitch_0
        :pswitch_0
        :pswitch_20
        :pswitch_1f
        :pswitch_1e
        :pswitch_1d
        :pswitch_0
        :pswitch_1c
        :pswitch_0
        :pswitch_0
        :pswitch_1b
        :pswitch_1a
        :pswitch_0
        :pswitch_0
        :pswitch_19
        :pswitch_18
        :pswitch_0
        :pswitch_17
        :pswitch_16
        :pswitch_15
        :pswitch_0
        :pswitch_14
        :pswitch_13
        :pswitch_12
        :pswitch_0
        :pswitch_11
        :pswitch_10
        :pswitch_f
        :pswitch_e
        :pswitch_d
        :pswitch_0
        :pswitch_c
        :pswitch_b
        :pswitch_a
        :pswitch_0
        :pswitch_9
        :pswitch_8
        :pswitch_7
        :pswitch_6
        :pswitch_5
        :pswitch_4
        :pswitch_3
        :pswitch_0
        :pswitch_0
        :pswitch_0
        :pswitch_0
        :pswitch_2
        :pswitch_0
        :pswitch_1
    .end packed-switch
.end method
