.class public final LX/3gw;
.super Ljava/lang/Object;
.source ""


# annotations
.annotation build Lcom/facebook/ultralight/AutoGeneratedSwitchAppModuleSubClass;
    value = 0x18
.end annotation


# direct methods
.method public static A00(ILX/0kw;)Ljava/lang/Object;
    .locals 1

    shr-int/lit8 v0, p0, 0x7

    and-int/lit8 v0, v0, 0xf

    if-nez v0, :cond_0

    invoke-static {p0, p1}, LX/3gw;->A01(ILX/0kw;)Ljava/lang/Object;

    move-result-object v0

    return-object v0

    :cond_0
    new-instance p0, Ljava/lang/IllegalArgumentException;

    const-string v0, "Invalid Static DI binding id"

    invoke-direct {p0, v0}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw p0
.end method

.method public static A01(ILX/0kw;)Ljava/lang/Object;
    .locals 0

    shr-int/lit8 p0, p0, 0x0

    and-int/lit8 p0, p0, 0x7f

    packed-switch p0, :pswitch_data_0

    :pswitch_0
    new-instance p1, Ljava/lang/IllegalArgumentException;

    const-string p0, "Invalid Static DI binding id"

    invoke-direct {p1, p0}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw p1

    :pswitch_1
    new-instance p0, LX/RBU;

    invoke-direct {p0, p1}, LX/RBU;-><init>(LX/0kw;)V

    return-object p0

    :pswitch_2
    invoke-static {p1}, LX/RBe;->A00(LX/0kw;)LX/RBe;

    move-result-object p0

    return-object p0

    :pswitch_3
    invoke-static {p1}, LX/RBn;->A00(LX/0kw;)LX/RBn;

    move-result-object p0

    return-object p0

    :pswitch_4
    invoke-static {p1}, LX/RCT;->A00(LX/0kw;)LX/RCT;

    move-result-object p0

    return-object p0

    :pswitch_5
    invoke-static {p1}, LX/RB4;->A00(LX/0kw;)LX/RB4;

    move-result-object p0

    return-object p0

    :pswitch_6
    invoke-static {p1}, LX/RC6;->A00(LX/0kw;)LX/RC6;

    move-result-object p0

    return-object p0

    :pswitch_data_0
    .packed-switch 0x1
        :pswitch_6
        :pswitch_0
        :pswitch_5
        :pswitch_4
        :pswitch_0
        :pswitch_0
        :pswitch_3
        :pswitch_0
        :pswitch_0
        :pswitch_2
        :pswitch_1
    .end packed-switch
.end method
